#!/usr/bin/env bash

#This script is created to calculate the % missing data from a strucutre file produced by the
#populations program in STACKS, just enter the file and go!

read -e -p "Enter the structure file you would like to calcualte the precent missing for: " file

if [ -e "$file" ]; then
	if [[ ${file: -4} == ".tsv" ]]; then
    	my0s=$(tail -n +3 $file | cut -f1,2 --complement | grep -o "0" | wc -l)
    	myindiv=$(tail -n +3 $file | wc -l)
    	myloci=$(head -n2 $file | sed 's/\t/\n/g' | wc -l)
    	myobs=$(expr $myindiv \* $myloci)

#Not quite sure if this floating point math will work on every computer, as it requires python (NOT 3)
    	percent_missing=$(python -c "print float($my0s)/float($myobs)")

    	echo "The is the precent missing data: "$percent_missing
    	echo "The number of individuals is: "$myindiv
    	echo "The number of loci is: "$myloci
    	echo "The is # of 0s: "$my0s
    	echo "The is # observations: "$myobs
    else
    	echo "";
    	echo "This is not a structure file generated by STACKS"
    	echo "";
    fi
else
    echo "";
    echo "Usage for $0 : You must enter a strucutre file (with file extension) geneterated by STACKS";
    echo "";
    exit 1;

fi